bg = love.graphics.newImage("assets/images/bg.png")
stars = love.graphics.newImage("assets/images/stars.png")
planetSprite = love.graphics.newImage("assets/images/planet.png")
playerSprite = love.graphics.newImage("assets/images/playerSprite.png")
playerAnimation = love.graphics.newImage("assets/images/playerAnimation.png")
gunSprite = love.graphics.newImage("assets/images/gunSprite.png")
gunAnimation = love.graphics.newImage("assets/images/gunAnimation.png")
bulletSprite = love.graphics.newImage("assets/images/bulletSprite.png")

bornSound = love.audio.newSource("assets/sounds/born.wav", "static")
deathSound = love.audio.newSource("assets/sounds/death.wav", "static")
selectSound = love.audio.newSource("assets/sounds/select.wav", "static")
shootSound = love.audio.newSource("assets/sounds/shoot.wav", "static")
walkSound = love.audio.newSource("assets/sounds/walk.wav", "static")
