bg = love.graphics.newImage("assets/images/bg.png")
stars = love.graphics.newImage("assets/images/stars.png")
planetSprite = love.graphics.newImage("assets/images/planet.png")
playerSprite = love.graphics.newImage("assets/images/playerSprite.png")
playerAnimation = love.graphics.newImage("assets/images/playerAnimation.png")
gunSprite = love.graphics.newImage("assets/images/gunSprite.png")
gunAnimation = love.graphics.newImage("assets/images/gunAnimation.png")
bulletSprite = love.graphics.newImage("assets/images/bulletSprite.png")
